# Generated by Django 5.2.8 on 2025-11-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
